# application.yml para ser utilizado nos serviços clientes Eureka que provem as palavras necessarias para criação da sentença
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
---
spring:
  profiles: subject
  application:
    name: word-server-subject
words: I,You,He,She,It

---
spring:
  profiles: verb
  application:
    name: word-server-verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  application:
    name: word-server-article
words: a,the

---
spring:
  profiles: adjective
  application:
    name: word-server-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application:
    name: word-server-noun
words: boat,book,vote,seat,backpack,partition,groundhog

---
spring:
  profiles: noun-hard-coded
  application:
    name: word-server-noun-hard-coded
words: icicle,refrigerator,blizzard,snowball